# Generated by Django 5.2.1 on 2025-05-10 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('company_size', models.CharField(blank=True, help_text='e.g., 1-10 employees, 50-200 employees', max_length=50)),
                ('website_url', models.URLField(blank=True, max_length=500, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('mission_statement', models.TextField(blank=True)),
                ('is_startup', models.BooleanField(default=False)),
                ('is_vc_firm', models.BooleanField(default=False, verbose_name='Is Venture Capital Firm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_business_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FundingOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('funding_amount_range', models.CharField(blank=True, help_text='e.g., $50k - $250k', max_length=100)),
                ('eligibility_criteria', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_opportunities', to='professional_app.businessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FundingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('funding_amount_sought', models.CharField(blank=True, help_text='e.g., $100k', max_length=100)),
                ('business_plan_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_requests', to='professional_app.businessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('employment_type', models.CharField(blank=True, choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('TEMPORARY', 'Temporary')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_listings', to='professional_app.businessprofile')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='job_listings', to='professional_app.skill')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalFeedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_feed_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('work_experience', models.JSONField(blank=True, default=list, help_text='List of work experiences, e.g., [{"title": "Engineer", "company": "Acme"}]')),
                ('education', models.JSONField(blank=True, default=list, help_text='List of education entries, e.g., [{"degree": "BSc", "school": "State U"}]')),
                ('resume_url', models.URLField(blank=True, max_length=500, null=True)),
                ('can_give_referrals', models.BooleanField(default=False)),
                ('looking_for_referrals', models.BooleanField(default=False)),
                ('is_mentor', models.BooleanField(default=False)),
                ('mentor_professions', models.CharField(blank=True, help_text='Comma-separated list of professions for mentorship', max_length=255)),
                ('is_mentee', models.BooleanField(default=False)),
                ('mentee_professions', models.CharField(blank=True, help_text='Comma-separated list of professions for mentee interest', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_detailed_professional_profile', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, related_name='professional_profiles', to='professional_app.skill')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('UNDER_REVIEW', 'Under Review'), ('INTERVIEWING', 'Interviewing'), ('OFFERED', 'Offered'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='APPLIED', max_length=20)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='professional_app.joblisting')),
            ],
            options={
                'unique_together': {('applicant', 'job_listing')},
            },
        ),
    ]
