# Generated by Django 5.2.1 on 2025-05-10 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_core_business_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_core_professional_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
